displayName: Agent
schemaName: cr4b8_agentlsuUDV
accessControlPolicy: ChatbotReaders
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cr4b8_agentlsuUDV.gpt.default

  aISettings:
    useModelKnowledge: false
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: High
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2025-11-01T10:34:56.0000000Z
template: default-2.1.0
language: 1046